### ISSUE TITLE
No communication with Landroid

### ISSUE THREAD

**Issue by metik237** [normen/homebridge-landroid#50]
Hi,

I am using a Homebridge for quite some time. Now that I bought Worx Landroid mower, I was so happy to see that there is a plugin for Homebridge.
Unfortunatelly I am still unable to use it, as there are no Landroid sensors visible in Homebridge when I configure that plugin.
The configuration is really straight forward.
- Install the plugin
- Add username, password (checked multiple times)
- choose cloud type, and thats it.

I can see the green light, but when I want to add the device to homekit, only Bridge appears. Additionally sensors are not visible in Homebridge.

Since my Landroid is not connected to Wi-Fi and is using celluar connection (Find my Landroid), could that be the case why it is not working for me?

Thank you in advance for your answers!

**Comment by Marksi73** [comment]
Please take a minute to read the other open issues. 
There has been a change breaking the whole plugin at the end of the last mowing season and unfortunately this plugin is still not fixed. Since it is all free for us to use we will have to wait until norman has time to fix this (or another, new plugin by another author is ready to use).
A lot of people are waiting for this ;)

**Comment by metik237** [comment]
Hey,
Thank you for that information. I really didnt check other issues :\
Does anyone knows if that plugin (normally) work if you use Find my Landroid (Celluar data)?

BR,

Matic
